### PR TITLE
Replaced corrupted EasyMeter dumps

### PR DESCRIPTION
**Pull request by lapawa**
As mentioned in #11 the EasyMeter dump was corrupted. This pull requests injects a fresh dump which can be parsed by sml_server.

### CODE REVIEW

**Comment by fkohlgrueber** [comment]
I just tried to parse the new dump using my parser (which I still haven't published). To me it seems like the data is still incomplete. 

```
0: Err: Checksum doesn't match
1: OK. Messages:
  OK
  OK
  OK
2: OK. Messages:
  OK
  OK
  OK
3: Err: Checksum doesn't match; end of transmission expected to have 4-byte alignment
4: Err: Checksum doesn't match; end of transmission expected to have 4-byte alignment
5: OK. Messages:
  OK
  OK
  OK
6: OK. Messages:
  OK
  OK
  OK
```

Seems like there are 7 sml transmissions in the dump. Four of them can be parsed, the others report a checksum mismatch when unpacking the transport format. I also tried disabling the checksum check, but then trying to parse the messages of these transmissions produces an error. According to the SML spec, the end marker of a transmission is required to have 4-byte alignment. Two of the three transmissions that fail to parse also don't respect that alignment, which could indicate missing data. 

Is it possible that your data collection is somewhat unreliable?

**Comment by lapawa** [comment]
That might be, but vzlogger works fine with it. 
A snipped from its log file vzlogger.log:

> [Dec 15 12:30:25][mtr0] Got 9 new readings from meter:
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:1.8.0*255/ObisIdentifier:1-0:1.8.0*255 value=2947782.15 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:2.8.0*255/ObisIdentifier:1-0:2.8.0*255 value=110073.16 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:16.7.0*255/ObisIdentifier:1-0:16.7.0*255 value=3019.52 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:36.7.0*255/ObisIdentifier:1-0:36.7.0*255 value=675.78 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:56.7.0*255/ObisIdentifier:1-0:56.7.0*255 value=2136.85 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:76.7.0*255/ObisIdentifier:1-0:76.7.0*255 value=206.88 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:32.7.0*255/ObisIdentifier:1-0:32.7.0*255 value=233.60 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:52.7.0*255/ObisIdentifier:1-0:52.7.0*255 value=233.20 ts=1639567825751
> [Dec 15 12:30:25][mtr0] Reading: id=1-0:72.7.0*255/ObisIdentifier:1-0:72.7.0*255 value=234.90 ts=1639567825751
> [Dec 15 12:30:25][chn0] Adding reading to queue (value=2947782.15 ts=1639567825751)
> [Dec 15 12:30:25][chn1] Adding reading to queue (value=110073.16 ts=1639567825751)
> [Dec 15 12:30:25][chn2] Adding reading to queue (value=675.78 ts=1639567825751)
> [Dec 15 12:30:25][chn3] Adding reading to queue (value=2136.85 ts=1639567825751)
> [Dec 15 12:30:25][chn4] Adding reading to queue (value=206.88 ts=1639567825751)
> [Dec 15 12:30:25][chn5] Adding reading to queue (value=3019.52 ts=1639567825751)

To achieve the dump I just followed the instruction from the README.md.
> dd if=/dev/ttyUSB0 of=yoursmldump.bin bs=1 count=4096 iflag=fullblock

**Comment by devZer0** [comment]
thanks. 

that's really weird, as vzlogger is using the same libsml. maybe it's simply ignoring the errors !?

do you get reads at exact same interval in vzlogger or do you see some missing ?

**Comment by devZer0** [comment]
@fkohlgrueber , your implementation seems to have better error handling

```
# cat EasyMeter_Q3A_A1064V1009.bin |./sml_server -
libsml: warning: could not read the whole file
129-129:199.130.3*255#ESY#
1-0:0.0.9*255#09 01 45 53 59 11 03 b5 99 a5 #
1-0:1.8.0*255#2941646.1614#Wh
1-0:2.8.0*255#110073.1603#Wh
1-0:16.7.0*255#810.26#W
1-0:36.7.0*255#505.23#W
1-0:56.7.0*255#63.19#W
1-0:76.7.0*255#241.83#W
129-129:199.130.5*255#1a 24 68 7a 27 7e 98 56 5e 10 93 05 5b ee 0f 70 4e 58 fd aa 3d d1 9d 4f af 3e e0 67 c1 64 c3 04 94 da e9 ea 15 66 ed 72 7d 23 6a af 5a b0 9a 5b #
1-0:0.0.0*255#1ESY1162232997#
1-0:32.7.0*255#232.5#V
1-0:52.7.0*255#230.7#V
1-0:72.7.0*255#232.5#V
129-129:199.240.6*255#01 07 1e #
129-129:199.130.3*255#ESY#
1-0:0.0.9*255#09 01 45 53 59 11 03 b5 99 a5 #
1-0:1.8.0*255#2941646.3734#Wh
1-0:2.8.0*255#110073.1603#Wh
1-0:16.7.0*255#763.08#W
1-0:36.7.0*255#486.22#W
1-0:56.7.0*255#51.67#W
1-0:76.7.0*255#225.18#W
129-129:199.130.5*255#1a 24 68 7a 27 7e 98 56 5e 10 93 05 5b ee 0f 70 4e 58 fd aa 3d d1 9d 4f af 3e e0 67 c1 64 c3 04 94 da e9 ea 15 66 ed 72 7d 23 6a af 5a b0 9a 5b #
1-0:0.0.0*255#1ESY1162232997#
1-0:32.7.0*255#232.4#V
1-0:52.7.0*255#230.6#V
1-0:72.7.0*255#232.2#V
129-129:199.240.6*255#01 07 1e #

**Comment by fkohlgrueber** [comment]
@devZer0 I was just about to post the verbose output of sml_server:

```
libsml: warning: could not read the whole file
SML file (1 SML messages, 408 bytes)
SML message  101
OBIS data
SML file (3 SML messages, 488 bytes)
SML message  101
SML message  701
SML message  201
OBIS data
129-129:199.130.3*255#ESY#
1-0:0.0.9*255#09 01 45 53 59 11 03 b5 99 a5 #
1-0:1.8.0*255#2941646.1614#Wh
1-0:2.8.0*255#110073.1603#Wh
1-0:16.7.0*255#810.26#W
1-0:36.7.0*255#505.23#W
1-0:56.7.0*255#63.19#W
1-0:76.7.0*255#241.83#W
129-129:199.130.5*255#1a 24 68 7a 27 7e 98 56 5e 10 93 05 5b ee 0f 70 4e 58 fd aa 3d d1 9d 4f af 3e e0 67 c1 64 c3 04 94 da e9 ea 15 66 ed 72 7d 23 6a af 5a b0 9a 5b #
1-0:0.0.0*255#1ESY1162232997#
1-0:32.7.0*255#232.5#V
1-0:52.7.0*255#230.7#V
1-0:72.7.0*255#232.5#V
129-129:199.240.6*255#01 07 1e #
SML file (3 SML messages, 488 bytes)
SML message  101
SML message  701
SML message  201
OBIS data
129-129:199.130.3*255#ESY#
1-0:0.0.9*255#09 01 45 53 59 11 03 b5 99 a5 #
1-0:1.8.0*255#2941646.3734#Wh
1-0:2.8.0*255#110073.1603#Wh
1-0:16.7.0*255#763.08#W
1-0:36.7.0*255#486.22#W
1-0:56.7.0*255#51.67#W
1-0:76.7.0*255#225.18#W
129-129:199.130.5*255#1a 24 68 7a 27 7e 98 56 5e 10 93 05 5b ee 0f 70 4e 58 fd aa 3d d1 9d 4f af 3e e0 67 c1 64 c3 04 94 da e9 ea 15 66 ed 72 7d 23 6a af 5a b0 9a 5b #
1-0:0.0.0*255#1ESY1162232997#
1-0:32.7.0*255#232.4#V
1-0:52.7.0*255#230.6#V
1-0:72.7.0*255#232.2#V
129-129:199.240.6*255#01 07 1e #
```

Seems like sml_server silently discards files that are invalid. The first (invalid) file is shown in the output, but it's not complete. The sml_server also seems to miss the last two files that are actually valid. Here's more detailed output produced by my parser:

```
0: Err: Checksum doesn't match
1: OK. Messages:
  OK
  OK
    ListEntry { obj_name: [129, 129, 199, 130, 3, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([69, 83, 89]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 9, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([9, 1, 69, 83, 89, 17, 3, 181, 153, 165]), value_signature: None }
    ListEntry { obj_name: [1, 0, 1, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(29416461614), value_signature: None }
    ListEntry { obj_name: [1, 0, 2, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(1100731603), value_signature: None }
    ListEntry { obj_name: [1, 0, 16, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(81026), value_signature: None }
    ListEntry { obj_name: [1, 0, 36, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(50523), value_signature: None }
    ListEntry { obj_name: [1, 0, 56, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(6319), value_signature: None }
    ListEntry { obj_name: [1, 0, 76, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(24183), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 130, 5, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([26, 36, 104, 122, 39, 126, 152, 86, 94, 16, 147, 5, 91, 238, 15, 112, 78, 88, 253, 170, 61, 209, 157, 79, 175, 62, 224, 103, 193, 100, 195, 4, 148, 218, 233, 234, 21, 102, 237, 114, 125, 35, 106, 175, 90, 176, 154, 91]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 0, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([49, 69, 83, 89, 49, 49, 54, 50, 50, 51, 50, 57, 57, 55]), value_signature: None }
    ListEntry { obj_name: [1, 0, 32, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2325), value_signature: None }
    ListEntry { obj_name: [1, 0, 52, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2307), value_signature: None }
    ListEntry { obj_name: [1, 0, 72, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2325), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 240, 6, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([1, 7, 30]), value_signature: None }
  OK
2: OK. Messages:
  OK
  OK
    ListEntry { obj_name: [129, 129, 199, 130, 3, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([69, 83, 89]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 9, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([9, 1, 69, 83, 89, 17, 3, 181, 153, 165]), value_signature: None }
    ListEntry { obj_name: [1, 0, 1, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(29416463734), value_signature: None }
    ListEntry { obj_name: [1, 0, 2, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(1100731603), value_signature: None }
    ListEntry { obj_name: [1, 0, 16, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(76308), value_signature: None }
    ListEntry { obj_name: [1, 0, 36, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(48622), value_signature: None }
    ListEntry { obj_name: [1, 0, 56, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(5167), value_signature: None }
    ListEntry { obj_name: [1, 0, 76, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(22518), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 130, 5, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([26, 36, 104, 122, 39, 126, 152, 86, 94, 16, 147, 5, 91, 238, 15, 112, 78, 88, 253, 170, 61, 209, 157, 79, 175, 62, 224, 103, 193, 100, 195, 4, 148, 218, 233, 234, 21, 102, 237, 114, 125, 35, 106, 175, 90, 176, 154, 91]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 0, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([49, 69, 83, 89, 49, 49, 54, 50, 50, 51, 50, 57, 57, 55]), value_signature: None }
    ListEntry { obj_name: [1, 0, 32, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2324), value_signature: None }
    ListEntry { obj_name: [1, 0, 52, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2306), value_signature: None }
    ListEntry { obj_name: [1, 0, 72, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2322), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 240, 6, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([1, 7, 30]), value_signature: None }
  OK
3: Err: end of transmission expected to have 4-byte alignment
4: Err: end of transmission expected to have 4-byte alignment
5: OK. Messages:
  OK
  OK
    ListEntry { obj_name: [129, 129, 199, 130, 3, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([69, 83, 89]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 9, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([9, 1, 69, 83, 89, 17, 3, 181, 153, 165]), value_signature: None }
    ListEntry { obj_name: [1, 0, 1, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(29416469715), value_signature: None }
    ListEntry { obj_name: [1, 0, 2, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(1100731603), value_signature: None }
    ListEntry { obj_name: [1, 0, 16, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(70308), value_signature: None }
    ListEntry { obj_name: [1, 0, 36, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(46486), value_signature: None }
    ListEntry { obj_name: [1, 0, 56, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(3477), value_signature: None }
    ListEntry { obj_name: [1, 0, 76, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(20344), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 130, 5, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([26, 36, 104, 122, 39, 126, 152, 86, 94, 16, 147, 5, 91, 238, 15, 112, 78, 88, 253, 170, 61, 209, 157, 79, 175, 62, 224, 103, 193, 100, 195, 4, 148, 218, 233, 234, 21, 102, 237, 114, 125, 35, 106, 175, 90, 176, 154, 91]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 0, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([49, 69, 83, 89, 49, 49, 54, 50, 50, 51, 50, 57, 57, 55]), value_signature: None }
    ListEntry { obj_name: [1, 0, 32, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2322), value_signature: None }
    ListEntry { obj_name: [1, 0, 52, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2306), value_signature: None }
    ListEntry { obj_name: [1, 0, 72, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2323), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 240, 6, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([1, 7, 30]), value_signature: None }
  OK
6: OK. Messages:
  OK
  OK
    ListEntry { obj_name: [129, 129, 199, 130, 3, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([69, 83, 89]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 9, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([9, 1, 69, 83, 89, 17, 3, 181, 153, 165]), value_signature: None }
    ListEntry { obj_name: [1, 0, 1, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(29416471626), value_signature: None }
    ListEntry { obj_name: [1, 0, 2, 8, 0, 255], status: Some(Status32(128)), val_time: None, unit: Some(30), scaler: Some(-4), value: I64(1100731603), value_signature: None }
    ListEntry { obj_name: [1, 0, 16, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(68786), value_signature: None }
    ListEntry { obj_name: [1, 0, 36, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(45829), value_signature: None }
    ListEntry { obj_name: [1, 0, 56, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(3240), value_signature: None }
    ListEntry { obj_name: [1, 0, 76, 7, 0, 255], status: None, val_time: None, unit: Some(27), scaler: Some(-2), value: I64(19716), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 130, 5, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([26, 36, 104, 122, 39, 126, 152, 86, 94, 16, 147, 5, 91, 238, 15, 112, 78, 88, 253, 170, 61, 209, 157, 79, 175, 62, 224, 103, 193, 100, 195, 4, 148, 218, 233, 234, 21, 102, 237, 114, 125, 35, 106, 175, 90, 176, 154, 91]), value_signature: None }
    ListEntry { obj_name: [1, 0, 0, 0, 0, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([49, 69, 83, 89, 49, 49, 54, 50, 50, 51, 50, 57, 57, 55]), value_signature: None }
    ListEntry { obj_name: [1, 0, 32, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2322), value_signature: None }
    ListEntry { obj_name: [1, 0, 52, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2305), value_signature: None }
    ListEntry { obj_name: [1, 0, 72, 7, 0, 255], status: None, val_time: None, unit: Some(35), scaler: Some(-1), value: U16(2320), value_signature: None }
    ListEntry { obj_name: [129, 129, 199, 240, 6, 255], status: None, val_time: None, unit: None, scaler: None, value: Bytes([1, 7, 30]), value_signature: None }
  OK
```

**Comment by devZer0** [comment]
>Seems like sml_server silently discards files that are invalid.

think we need to know if this is a problem in sml_server or in libsml. i can have a look later on if you don't want to dig into it

**Comment by fkohlgrueber** [comment]
I had a quick look. Here's what I found:

- libsml doesn't check the checksum of transmissions (see [here](https://github.com/volkszaehler/libsml/blob/master/sml/src/sml_transport.c#L100-L104)). That's the reason why the first (corrupt) message is processed by libsml. 
- Regarding corrupt files: It seems like libsml creates an empty file and then adds successfully parsed messages to it. That's why for the first file, it still reports the first message (101) and nothing else.
- libsml's transport decoder expects escape codes to be aligned to 4 bytes (see [here](https://github.com/volkszaehler/libsml/blob/master/sml/src/sml_transport.c#L93). If the alignment is off (e.g. due to missing bytes), the end of a file will not be detected (that's why the last two complete files aren't detected)

**Comment by devZer0** [comment]
thanks for looking into it

>libsml doesn't check the checksum of transmissions (see here). 
>That's the reason why the first (corrupt) message is processed by libsml.

you mean , it does not check checksum of whole telegram but only on single messages ?  there is checksum checking in sml_message for a while , see https://github.com/volkszaehler/libsml/commit/2f4ac143ff53b053725f196f77eb0f804a480e72

>Regarding corrupt files: It seems like libsml creates an empty file and then adds successfully 
>parsed messages to it. That's why for the first file, it still reports the first message (101) and nothing else.

what exactly do you mean by "empty file" ?

>libsml's transport decoder expects escape codes to be aligned to 4 bytes (see here. If the alignment is 
>off (e.g. due to missing bytes), the end of a file will not be detected (that's why the last two complete 
>files aren't detected)

ah, ok. anyhow, if some byte(s) is/are missing, i don't see a real problem when messages getting skipped. if transmission quality sucks, it should be fixed at the phy. layer.

**Comment by fkohlgrueber** [comment]
> you mean , it does not check checksum of whole telegram but only on single messages ? there is checksum checking in sml_message for a while , see volkszaehler/libsml@2f4ac14

yes, exactly. Checking the transport's crc would allow to detect transmission errors earlier, but I think only checking the crc in sml_message is fine too.

> what exactly do you mean by "empty file" ?

An sml_file object that doesn't contain any sml_messages.

> ah, ok. anyhow, if some byte(s) is/are missing, i don't see a real problem when messages getting skipped. if transmission quality sucks, it should be fixed at the phy. layer.

In my project, I want to see if messages couldn't be parsed (so that I can see whether the phy. layer works reliably). That's really a nice-to-have though and skipping is generally fine.

How do we proceed with the EasyMeter dumps?

**Comment by devZer0** [comment]
>How do we proceed with the EasyMeter dumps?

should we add it as an example of "real world, but corrupted data" and open a ticket for libsml for enhancement of crc checking & error reporting ?

**Comment by fkohlgrueber** [comment]
Sounds good!

**Comment by devZer0** [comment]
hi. i postponed merging  your commit because i would rather like to see it fixed in libsml first.  hope this is ok for you.

**Pull request merged**
